openapi: 3.0.0
info:
  title: Timebank
  description: Timebank API documentation
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    PersonDto:
      type: object
      properties:
        id:
          type: number
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        user_type:
          type: string
        client_id:
          type: number
        holiday_calendar_id:
          type: number
        monday:
          type: number
        tuesday:
          type: number
        wednesday:
          type: number
        thursday:
          type: number
        friday:
          type: number
        saturday:
          type: number
        sunday:
          type: number
        active:
          type: boolean
        default_role:
          type: number
        cost:
          type: number
        language:
          type: string
        created_by:
          type: number
        updated_by:
          type: number
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        start_date:
          type: string
      required:
        - id
        - first_name
        - last_name
        - email
        - user_type
        - client_id
        - holiday_calendar_id
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
        - active
        - default_role
        - cost
        - language
        - created_by
        - updated_by
        - created_at
        - updated_at
        - start_date
    TimeEntry:
      type: object
      properties:
        externalId:
          type: string
        person:
          type: number
        internalTime:
          type: number
        projectTime:
          type: number
        logged:
          type: number
        expected:
          type: number
        total:
          type: number
        date:
          format: date-time
          type: string
      required:
        - externalId
        - person
        - internalTime
        - projectTime
        - logged
        - expected
        - total
        - date
    TimeEntryTotalId:
      type: object
      properties:
        year:
          type: number
        month:
          type: number
        week:
          type: number
    TimeEntryTotalDto:
      type: object
      properties:
        _id:
          $ref: '#/components/schemas/TimeEntryTotalId'
        total:
          type: number
        logged:
          type: number
        expected:
          type: number
        internalTime:
          type: number
        projectTime:
          type: number
      required:
        - total
        - logged
        - expected
        - internalTime
        - projectTime
paths:
  /timebank/persons:
    get:
      operationId: TimebankController_getPersons
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonDto'
      tags:
        - timebank
  '/timebank/entries/{personId}':
    get:
      operationId: TimebankController_getEntries
      parameters:
        - name: personId
          required: true
          in: path
          schema:
            type: string
        - name: before
          required: false
          in: query
          schema:
            type: string
        - name: after
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeEntry'
      tags:
        - timebank
  /timebank/sync:
    post:
      operationId: TimebankController_syncWorkTime
      parameters:
        - name: before
          required: false
          in: query
          schema:
            type: string
        - name: after
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - timebank
  '/timebank/total/{personId}':
    get:
      operationId: TimebankController_getTotal
      parameters:
        - name: personId
          required: true
          in: path
          schema:
            type: string
        - name: retention
          required: false
          in: query
          description: Default value is ALL_TIME
          schema:
            enum:
              - ALL_TIME
              - YEAR
              - MONTH
              - WEEK
            type: string
      responses:
        '200':
          description: |-
            When getting total from all the time,
                              _id field will be null, otherwise it will be
                              combination of year and month or year and week
                              depending on retention parameter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeEntryTotalDto'
      tags:
        - timebank
  /system/ping:
    get:
      operationId: SystemController_getPersons
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      tags:
        - system
